echo off
set CASPER_CMD=c:\Outils\casperjs-1.1-b3\batchbin\casperjs.bat scrapConstructor.js 
echo %time%

call %CASPER_CMD% scrapConstructor.js /cote-voitures-abarth----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-acrea----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-aixam----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-alfa+romeo----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-alpine+renault----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-aro----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-artega----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-aston+martin----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-audi----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-austin----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-autobianchi----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-auverland----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-bellier----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-bentley----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-bertone----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-bmw----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-bugatti----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-buick----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-cadillac----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-carver----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-casalini----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-caterham----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-chatenet----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-chevrolet----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-chrysler----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-citroen----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-corvette----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-dacia----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-daewoo----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-daihatsu----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-dangel----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-de+la+chapelle----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-de+tomaso----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-dodge----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-donkervoort----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-ebro----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-fam+automobiles----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-ferrari----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-fiat----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-fisker----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-ford----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-ford+usa----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-fso----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-gillet----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-ginetta----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-gme----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-grandin----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-grecav----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-hommell----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-honda----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-hummer----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-hyundai----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-infiniti----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-isuzu----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-italcar----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-jaguar----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-jdm+simpa----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-jeep----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-kia----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-lada----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-lamborghini----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-lancia----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-land+rover----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-landwind----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-lexus----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-ligier----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-lincoln----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-lotus----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-mahindra----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-maruti----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-maserati----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-matra----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-maybach----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-mazda----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-mclaren----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-mega----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-mercedes----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-mg----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-microcar----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-mini----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-mitsubishi----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-morgan----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-morris----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-mvs----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-nissan----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-opel----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-pagani----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-peugeot----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-pgo----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-piaggio----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-polski----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-pontiac----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-porsche----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-proton----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-renault----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-rolls+royce----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-rover----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-saab----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-santana----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-savel----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-seat----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-secma----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-skoda----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-smart----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-ssangyong----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-subaru----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-suzuki----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-tesla----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-toyota----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-tvr----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-umm----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-venturi----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-volkswagen----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-volvo----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-westfield----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-wiesmann----.html
call %CASPER_CMD% scrapConstructor.js /cote-voitures-zastava----.html